#!/bin/bash
#SBATCH --account=egi6035
#SBATCH --job-name="SETTE_job"
#SBATCH --constraint=GENOA
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=NPROCS
#SBATCH --cpus-per-task=1
#SBATCH --threads-per-core=1
#SBATCH --time=1:00:00

module purge

module load cpe/23.05
module load craype-x86-genoa
module load craype-network-ofi
module load libfabric/1.15.2.0
module load PrgEnv-intel/8.4.0
module load cray-libsci/23.05.1.4
module load cray-mpich/8.1.26
module load cray-dsmml/0.2.2
module load cray-fftw/3.3.10.4
module load cray-hdf5-parallel/1.12.2.1
module load cray-netcdf-hdf5parallel/4.9.0.1
module load craype/2.7.21
module load gcc/13.2.0

module list

ldd ./nemo

##########################################################################
#
# Test specific settings. Do not hand edit these lines; the fcm_job.sh script will set these
# (via sed operating on this template job file). 
#
  OCEANCORES=NPROCS
  export SETTE_DIR=DEF_SETTE_DIR
#
# set up mpp computing environment
#
# Local settings for machine BULL (TITANE at CCRT France)
#
export MPIRUN="srun"

#
# load sette functions (only post_test_tidyup needed)
#
  . ${SETTE_DIR}/all_functions.sh
#

# modules to load

# Don't remove neither change the following line
# BODY

#
# These variables are needed by post_test_tidyup function in all_functions.sh
#
  export EXE_DIR=DEF_EXE_DIR
  export INPUT_DIR=DEF_INPUT_DIR
  export CONFIG_DIR=DEF_CONFIG_DIR
  export TOOLS_DIR=DEF_TOOLS_DIR
  export NEMO_VALIDATION_DIR=DEF_NEMO_VALIDATION
  export NEW_CONF=DEF_NEW_CONF
  export CMP_NAM=DEF_CMP_NAM
  export TEST_NAME=DEF_TEST_NAME
#
# end of set up
###############################################################
#
# change to the working directory 
#
cd ${EXE_DIR}

  echo Running on host `hostname`
  echo Time is `date`
  echo Directory is `pwd`

  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CRAY_LD_LIBRARY_PATH
  echo $LD_LIBRARY_PATH

# 
#  Run the parallel MPI executable 
#
  echo "Running time ${MPIRUN} ./nemo"
#
  if [ MPI_FLAG == "yes" ]; then
     time ${MPIRUN} ./nemo
  else
     time ./nemo
  fi

#
  post_test_tidyup

# END_BODY
# Don't remove neither change the previous line


  exit

