#!/bin/bash
#MSUB -r rebuild_nemo
#MSUB -o rebuild_nemo.o%j
#MSUB -e rebuild_nemo.e%j
#MSUB -n 7
#MSUB -x
#MSUB -T 5400
#MSUB -A gen6035
#MSUB -q rome
#MSUB -m store,workflash,scratch

export OMP_NUM_THREADS=NTHREADS
indir=INDIR
nam_rebuild=NAMELIST
liceberg=LBERG

ulimit -s unlimited
ulimit -n NOPEN

. ~/.bashrc

module purge
module load mpi/openmpi/4.0.5
module load hdf5/1.8.20
module load netcdf-fortran/4.4.4

conda activate nemo

ccc_mprun ${indir}/mpp_rebuild_nemo.exe $nam_rebuild || exit $?

if [ ! -z $liceberg ]; then
    echo 'rebuild iceberg'

    # get filebase
    zFILEBASE=`grep filebase $nam_rebuild`
    FILEBASE=`echo ${zFILEBASE#*=} | sed "s/'//g"` 
    
    # get ndomain
    zNDOMAIN=`grep ndomain $nam_rebuild`
    NDOMAIN=${zNDOMAIN#*=}

    # add icebergs
    python ${indir}/icb_combrest.py -f ${FILEBASE}_ -n ${NDOMAIN} -o ${FILEBASE}.nc || exit $?
fi

RC=$?

exit $RC
