#!/bin/bash
#SBATCH --job-name=mpp_reb_nemo
#SBATCH --output=mpp_reb_%j.out
#SBATCH --time=20:00
#SBATCH --account=n01-CLASS
#SBATCH --partition=standard
#SBATCH --qos=short

#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks=16

export OMP_NUM_THREADS=NTHREADS
indir=INDIR
nam_rebuild=NAMELIST
liceberg=LBERG

ulimit -s unlimited

module load cray-mpich/8.1.23
module load cray-hdf5-parallel/1.12.2.1
module load cray-netcdf-hdf5parallel/4.9.0.1


srun ${indir}/mpp_rebuild_nemo.exe $nam_rebuild || exit $?

if [ ! -z $liceberg ]; then

    # Needs setconda to be defined as an alias or bash function
    # to set-up an appropriate python environment
    export PATH="/work/n01/shared/acc/CONDA/bin:$PATH"
    echo 'rebuild iceberg'

    # get filebase
    zFILEBASE=`grep filebase $nam_rebuild`
    FILEBASE=`echo ${zFILEBASE#*=} | sed "s/'//g"` 
    
    # get ndomain
    zNDOMAIN=`grep ndomain $nam_rebuild`
    NDOMAIN=${zNDOMAIN#*=}

    # add icebergs
    python ${indir}/icb_combrest.py -f ${FILEBASE}_ -n ${NDOMAIN} -o ${FILEBASE}.nc || exit $?
fi

RC=$?

exit $RC
