
# HPC & configs/testcases to be tested in parallel with SETTE

.parallel_HPC_CFG:ALL:
  variables:
    CONFIG: ${NEMO_CONFIG}
  parallel:
    matrix:
      - HPC: [ecmwf]

.parallel_HPC_CFG:RESTART:
  variables:
    CONFIG: ${NEMO_CONFIG}
  parallel:
    matrix:
      - HPC: [ecmwf]

.parallel_HPC_CFG:REPRO:
  variables:
    CONFIG: ${NEMO_CONFIG}
  parallel:
    matrix:
      - HPC: [ecmwf]

.parallel_HPC_CFG:CORRUPT:
  variables:
    CONFIG: ${NEMO_CONFIG}
  parallel:
    matrix:
      - HPC: [ecmwf]

.parallel_HPC_CFG:PHYOPTS:
  variables:
    CONFIG: ${NEMO_CONFIG}
  parallel:
    matrix:
      - HPC: [ecmwf]

# variables declared hereafter will be avaible in all jobs
# these variables are needed for each HPC to be tested:
# - HPC_SETTE_CFG: SETTE param.cfg file path

variables:
  # METEO-FRANCE BELENOS (INTEL2018+INTELMPI)
  METFRA_SETTE_CFG: "/home/ext/mr/smer/samsong/SRC/NEMO/main/sette/param_${NEMO_COMPILER}.ci"
  # ECMWF AA/B/C/D (GCC12+OPENMPI & INTEL2021+OPENMPI)
  ECMWF_SETTE_CFG: "/home/ar0s/SRC/NEMO/main/sette/param_${NEMO_COMPILER}.ci"
